[package]
name = "notation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2"
chrono = "0.4"
tui = "0.18"
crossterm = "0.24"
